export const LIVEKIT_ACTIVE_SPEAKER_SOURCE = "LIVEKIT_ACTIVE_SPEAKER" as const;
export const VOXIMPLANT_MIC_ACTIVITY_SOURCE = "VOXIMPLANT_MIC_ACTIVITY" as const;
export const VOX_REMOTE_STREAM_ACTIVITY_SOURCE = "VOX_REMOTE_STREAM_ACTIVITY" as const;

export const AUDIO_ACTIVITY_SOURCES = {
  LIVEKIT_ACTIVE_SPEAKER: LIVEKIT_ACTIVE_SPEAKER_SOURCE,
  VOXIMPLANT_MIC_ACTIVITY: VOXIMPLANT_MIC_ACTIVITY_SOURCE,
  VOX_REMOTE_STREAM_ACTIVITY: VOX_REMOTE_STREAM_ACTIVITY_SOURCE,
} as const;

export type AudioActivitySource =
  (typeof AUDIO_ACTIVITY_SOURCES)[keyof typeof AUDIO_ACTIVITY_SOURCES];

export const DEFAULT_AUDIO_ACTIVITY_SOURCE = LIVEKIT_ACTIVE_SPEAKER_SOURCE;

export function isRemoteStreamActivitySource(source: string) {
  return source === VOX_REMOTE_STREAM_ACTIVITY_SOURCE;
}
