export const VOX_SPEAKING_ON_LEVEL = 10;
export const VOX_SPEAKING_OFF_LEVEL = 6;
export const VOX_END_DEBOUNCE_MS = 800;

export const TELEMETRY_NORMALIZE_MERGE_GAP_MS = 1200;
export const TELEMETRY_MIN_INTERVAL_MS = 300;

export const REMOTE_SPEAKING_LEVEL_THRESHOLD = 8;
export const REMOTE_SPEAKING_RELEASE_MULTIPLIER = 0.6;

export const AUDIO_LEVEL_RMS_TO_PERCENT_MULTIPLIER = 300;

export const TELEMETRY_CALIBRATION = {
  voxSpeakingOnLevel: VOX_SPEAKING_ON_LEVEL,
  voxSpeakingOffLevel: VOX_SPEAKING_OFF_LEVEL,
  voxEndDebounceMs: VOX_END_DEBOUNCE_MS,
  mergeGapMs: TELEMETRY_NORMALIZE_MERGE_GAP_MS,
  minIntervalMs: TELEMETRY_MIN_INTERVAL_MS,
  remoteSpeakingThreshold: REMOTE_SPEAKING_LEVEL_THRESHOLD,
  remoteSpeakingReleaseMultiplier: REMOTE_SPEAKING_RELEASE_MULTIPLIER,
};
