export const OUTCOMES = Object.freeze({
  VALIDATION_OK: "VALIDATION_OK",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  VALIDATION_TIMEOUT: "VALIDATION_TIMEOUT",
  VALIDATION_ALREADY_RUNNING: "VALIDATION_ALREADY_RUNNING",
  VALIDATION_STALE_LOCK: "VALIDATION_STALE_LOCK",
  PRISMA_GENERATION_FAILED: "PRISMA_GENERATION_FAILED",
  PRISMA_CLIENT_INTEGRITY_FAILED: "PRISMA_CLIENT_INTEGRITY_FAILED",
  CHILD_CLEANUP_FAILED: "CHILD_CLEANUP_FAILED",
  VALIDATION_CANCELLED: "VALIDATION_CANCELLED",
});

export const EXIT_CODES = Object.freeze({
  [OUTCOMES.VALIDATION_OK]: 0,
  [OUTCOMES.VALIDATION_FAILED]: 1,
  [OUTCOMES.VALIDATION_TIMEOUT]: 2,
  [OUTCOMES.VALIDATION_ALREADY_RUNNING]: 3,
  [OUTCOMES.VALIDATION_STALE_LOCK]: 4,
  [OUTCOMES.PRISMA_GENERATION_FAILED]: 5,
  [OUTCOMES.PRISMA_CLIENT_INTEGRITY_FAILED]: 6,
  [OUTCOMES.CHILD_CLEANUP_FAILED]: 7,
  [OUTCOMES.VALIDATION_CANCELLED]: 8,
});

export const TIMEOUT_LAYERS = Object.freeze({
  STEP_TIMEOUT: "STEP_TIMEOUT",
  RUN_TIMEOUT: "RUN_TIMEOUT",
});

export const LOCK_KINDS = Object.freeze({
  VALIDATION: "validation",
  PRISMA_GENERATE: "prisma-generate",
});

export function exitCodeForOutcome(outcome) {
  return Object.hasOwn(EXIT_CODES, outcome) ? EXIT_CODES[outcome] : 1;
}
